version: '3.8'

services:
  db:
    container_name: jobhunter-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: JobHunterDb2
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d JobHunterDb2"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jobhunter-network

networks:
  jobhunter-network:
    driver: bridge

volumes:
  pgdata:
